Fix and improve bytes to string conversion
Fix the following error when dropping a page into the scrollview:
```
Traceback (most recent call last):
  File "[...]/pdfshuffler/pdfshuffler.py", line 930, in sw_dnd_received_data
    data = data.split('\n;\n')
TypeError: a bytes-like object is required, not 'str'
```

Use SelectionData::get_uris() where appropiate.
Remove now unneeded decode() call.