Fix DrawingAreaWidget error
If dialog is closed too fast before drawing area has allocated space
there will be a error:
"AttributeError: 'NoneType' object has no attribute 'get_value'"
It did however not cause any issues.