Fix: AttributeError: module 'img2pdf' has no attribute 'AlphaChannelError'
* img2pdf.AlphaChannelError was added in
  https://gitlab.mister-muffin.de/josch/img2pdf/commit/0102248
  which is only available in img2pdf 0.3.4.
* Close #208